version: "3.9"

networks:
  web:
    external: true

services:
  frontend:
    build:
      context: ../../apps/frontend
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_BASE_URL=${NEXT_PUBLIC_API_BASE_URL}
      - PORT=${FRONTEND_PORT:-3000}
    expose:
      - "${FRONTEND_PORT:-3000}"
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.services.lucai-frontend.loadbalancer.server.port=${FRONTEND_PORT:-3000}"
      - "traefik.http.routers.lucai-frontend.rule=Host(`${FRONTEND_HOST}`)"
      - "traefik.http.routers.lucai-frontend.entrypoints=websecure"
      - "traefik.http.routers.lucai-frontend.tls=true"
      - "traefik.http.routers.lucai-frontend.tls.certresolver=leresolver"
      # HTTP → HTTPS redirect
      - "traefik.http.routers.lucai-frontend-http.rule=Host(`${FRONTEND_HOST}`)"
      - "traefik.http.routers.lucai-frontend-http.entrypoints=web"
      - "traefik.http.routers.lucai-frontend-http.middlewares=lucai-frontend-https-redirect"
      - "traefik.http.middlewares.lucai-frontend-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.lucai-frontend-https-redirect.redirectscheme.permanent=true"
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1G
    networks:
      - web
