version: "3.9"

networks:
  web:
    external: true
  internal:
    internal: true

services:
  backend:
    build:
      context: ../../apps/backend
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - PORT=${BACKEND_PORT:-8080}
      - API_PREFIX=${API_PREFIX:-/api}
      - CORS_ALLOW_ORIGINS=${CORS_ALLOW_ORIGINS}
      - ASK_SERVICE_URL=http://ask-service:9000
      - DB_PATH=/data/lucai-chat/lucai.db
    expose:
      - "${BACKEND_PORT:-8080}"
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.services.lucai-backend.loadbalancer.server.port=${BACKEND_PORT:-8080}"
      - "traefik.http.routers.lucai-backend.rule=Host(`${BACKEND_HOST}`)"
      - "traefik.http.routers.lucai-backend.entrypoints=websecure"
      - "traefik.http.routers.lucai-backend.tls=true"
      - "traefik.http.routers.lucai-backend.tls.certresolver=leresolver"
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 512M
    networks:
      - web
      - internal
    volumes:
      - lucai_data:/data
    depends_on:
      - ask-service

  frontend:
    build:
      context: ../../apps/frontend
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_BASE_URL=${NEXT_PUBLIC_API_BASE_URL}
      - PORT=${FRONTEND_PORT:-3000}
    depends_on:
      - backend
    expose:
      - "${FRONTEND_PORT:-3000}"
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.services.lucai-frontend.loadbalancer.server.port=${FRONTEND_PORT:-3000}"
      - "traefik.http.routers.lucai-frontend.rule=Host(`${FRONTEND_HOST}`)"
      - "traefik.http.routers.lucai-frontend.entrypoints=websecure"
      - "traefik.http.routers.lucai-frontend.tls=true"
      - "traefik.http.routers.lucai-frontend.tls.certresolver=leresolver"
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1G
    networks:
      - web

  ask-service:
    build:
      context: ../../apps/sql_assistant
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - DB_URL=${ASK_DB_URL:-sqlite:///file:/data/lucai-chat/lucai.db?mode=ro&uri=true}
      - LLM_BASE_URL=${LLM_BASE_URL}
      - LLM_API_KEY=${LLM_API_KEY:-none}
      - LLM_MODEL=${LLM_MODEL:-local}
    expose:
      - "9000"
    restart: always
    labels:
      - "traefik.enable=false"
    volumes:
      - lucai_data:/data
    networks:
      - internal

volumes:
  lucai_data:
